/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { PainterStyle, PainterStyleID, TFDAQuestion, TFDADocument, ModificationRule } from './types';

export const PAINTER_STYLES: PainterStyle[] = [
  {
    id: 'modern_minimal',
    nameEn: 'Modern Minimal',
    nameZh: '現代簡約',
    primary: '#000000',
    secondary: '#ffffff',
    accent: '#3b82f6',
    background: '#f8fafc',
    text: '#0f172a',
    fontFamily: 'Inter, sans-serif',
    borderRadius: '8px',
    borderWidth: '1px',
    shadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
    animationCurve: 'cubic-bezier(0.4, 0, 0.2, 1)',
  },
  {
    id: 'van_gogh',
    nameEn: 'Van Gogh',
    nameZh: '梵谷',
    primary: '#1e3a8a',
    secondary: '#facc15',
    accent: '#9a3412',
    background: '#0c1a3a',
    text: '#e2e8f0',
    fontFamily: 'Georgia, serif',
    borderRadius: '24px',
    borderWidth: '3px',
    shadow: '0 0 20px rgba(250, 204, 21, 0.3)',
    animationCurve: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
  },
  {
    id: 'mondrian',
    nameEn: 'Artistic Flair (Mondrian)',
    nameZh: '藝術風範 (蒙德里安)',
    primary: '#E63946', // Mondrian Red
    secondary: '#F8F9FA', // Mondrian White
    accent: '#FFD60A', // Mondrian Yellow
    background: '#EAE7E1', // Mondrian Bg
    text: '#141414', // Mondrian Black
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
    borderRadius: '0px',
    borderWidth: '4px',
    shadow: 'none',
    animationCurve: 'steps(1)',
  },
  {
    id: 'hokusai',
    nameEn: 'Hokusai',
    nameZh: '葛飾北齋',
    primary: '#0f172a',
    secondary: '#334155',
    accent: '#cbd5e1',
    background: '#f1f5f9',
    text: '#020617',
    fontFamily: '"Times New Roman", serif',
    borderRadius: '4px',
    borderWidth: '2px',
    shadow: '0 4px 0px #0f172a',
    animationCurve: 'ease-in-out',
  },
  {
    id: 'banksy',
    nameEn: 'Banksy',
    nameZh: '班克斯',
    primary: '#18181b',
    secondary: '#71717a',
    accent: '#db2777',
    background: '#27272a',
    text: '#f4f4f5',
    fontFamily: 'monospace',
    borderRadius: '2px',
    borderWidth: '3px',
    shadow: '0 4px 10px rgba(0,0,0,0.5)',
    animationCurve: 'steps(4)',
    noise: true,
  },
  {
    id: 'kusama',
    nameEn: 'Yayoi Kusama',
    nameZh: '草間彌生',
    primary: '#ef4444',
    secondary: '#ffffff',
    accent: '#000000',
    background: '#ffffff',
    text: '#000000',
    fontFamily: 'Impact, sans-serif',
    borderRadius: '50%',
    borderWidth: '2px',
    shadow: 'none',
    animationCurve: 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
  },
  // Add more styles to reach 20
  {
    id: 'monet',
    nameEn: 'Monet',
    nameZh: '莫內',
    primary: '#a5b4fc',
    secondary: '#dcfce7',
    accent: '#fef9c3',
    background: '#f8fafc',
    text: '#334155',
    fontFamily: 'serif',
    borderRadius: '16px',
    borderWidth: '0px',
    shadow: '0 10px 15px -3px rgba(165, 180, 252, 0.4)',
    animationCurve: 'ease-out',
  },
  {
    id: 'picasso',
    nameEn: 'Picasso',
    nameZh: '畢卡索',
    primary: '#ea580c',
    secondary: '#0891b2',
    accent: '#facc15',
    background: '#fff7ed',
    text: '#431407',
    fontFamily: 'cursive',
    borderRadius: '30px 10px 40px 5px',
    borderWidth: '2px',
    shadow: '5px 5px 0px #ea580c',
    animationCurve: 'cubic-bezier(0.4, 0, 1, 1)',
  },
  {
    id: 'dali',
    nameEn: 'Dali',
    nameZh: '達利',
    primary: '#451a03',
    secondary: '#92400e',
    accent: '#fcd34d',
    background: '#fffbeb',
    text: '#451a03',
    fontFamily: 'serif',
    borderRadius: '100px 20px 100px 20px',
    borderWidth: '1px',
    shadow: '10px 10px 30px rgba(0,0,0,0.1)',
    animationCurve: 'cubic-bezier(0.1, 0.7, 1.0, 0.1)',
  },
  {
    id: 'klimt',
    nameEn: 'Klimt',
    nameZh: '克林姆',
    primary: '#ca8a04',
    secondary: '#fef08a',
    accent: '#000000',
    background: '#1a1a1a',
    text: '#fef08a',
    fontFamily: 'fantasy',
    borderRadius: '12px',
    borderWidth: '4px',
    shadow: '0 0 15px #ca8a04',
    animationCurve: 'ease-in-out',
  },
  {
    id: 'basquiat',
    nameEn: 'Basquiat',
    nameZh: '巴斯奇亞',
    primary: '#000000',
    secondary: '#ffffff',
    accent: '#ef4444',
    background: '#e5e7eb',
    text: '#000000',
    fontFamily: 'monospace',
    borderRadius: '2px',
    borderWidth: '5px',
    shadow: 'none',
    animationCurve: 'steps(2)',
  },
  {
    id: 'warhol',
    nameEn: 'Warhol',
    nameZh: '沃荷',
    primary: '#db2777',
    secondary: '#22c55e',
    accent: '#eab308',
    background: '#ffffff',
    text: '#000000',
    fontFamily: 'sans-serif',
    borderRadius: '4px',
    borderWidth: '2px',
    shadow: '10px 10px 0px #db2777',
    animationCurve: 'ease-in',
  },
  {
    id: 'kahlo',
    nameEn: 'Kahlo',
    nameZh: '卡蘿',
    primary: '#b91c1c',
    secondary: '#15803d',
    accent: '#eab308',
    background: '#fff1f2',
    text: '#450a0a',
    fontFamily: 'serif',
    borderRadius: '20px',
    borderWidth: '2px',
    shadow: '0 4px 6px rgba(185, 28, 28, 0.3)',
    animationCurve: 'ease-out',
  },
  {
    id: 'davinci',
    nameEn: 'Da Vinci',
    nameZh: '達文西',
    primary: '#451a03',
    secondary: '#78350f',
    accent: '#d97706',
    background: '#fafaf9',
    text: '#1c1917',
    fontFamily: 'Georgia, serif',
    borderRadius: '4px',
    borderWidth: '1px',
    shadow: '0 2px 4px rgba(0,0,0,0.05)',
    animationCurve: 'ease-in-out',
  },
  {
    id: 'rembrandt',
    nameEn: 'Rembrandt',
    nameZh: '林布蘭',
    primary: '#27272a',
    secondary: '#52525b',
    accent: '#a16207',
    background: '#09090b',
    text: '#d4d4d8',
    fontFamily: 'serif',
    borderRadius: '2px',
    borderWidth: '1px',
    shadow: 'inset 0 0 40px rgba(0,0,0,0.5)',
    animationCurve: 'ease',
  },
  {
    id: 'matisse',
    nameEn: 'Matisse',
    nameZh: '馬諦斯',
    primary: '#2563eb',
    secondary: '#dc2626',
    accent: '#eab308',
    background: '#ffffff',
    text: '#000000',
    fontFamily: 'sans-serif',
    borderRadius: '40px',
    borderWidth: '0px',
    shadow: 'none',
    animationCurve: 'ease-in-out',
  },
  {
    id: 'rothko',
    nameEn: 'Rothko',
    nameZh: '羅伯特',
    primary: '#7f1d1d',
    secondary: '#450a0a',
    accent: '#18181b',
    background: '#450a0a',
    text: '#fca5a5',
    fontFamily: 'sans-serif',
    borderRadius: '0px',
    borderWidth: '0px',
    shadow: 'none',
    animationCurve: 'ease',
  },
  {
    id: 'pollock',
    nameEn: 'Pollock',
    nameZh: '波洛克',
    primary: '#000000',
    secondary: '#ffffff',
    accent: '#ef4444',
    background: '#ffffff',
    text: '#000000',
    fontFamily: 'sans-serif',
    borderRadius: '0px',
    borderWidth: '0px',
    shadow: 'none',
    animationCurve: 'cubic-bezier(0.1, 2.0, 0.5, 0.5)',
  },
  {
    id: 'o_keeffe',
    nameEn: 'O\'Keeffe',
    nameZh: '歐姬芙',
    primary: '#ec4899',
    secondary: '#fb923c',
    accent: '#8b5cf6',
    background: '#fff7ed',
    text: '#500724',
    fontFamily: 'serif',
    borderRadius: '60px 40px 80px 20px',
    borderWidth: '0px',
    shadow: 'none',
    animationCurve: 'ease-in-out',
  },
  {
    id: 'magritte',
    nameEn: 'Magritte',
    nameZh: '馬格利特',
    primary: '#1e293b',
    secondary: '#60a5fa',
    accent: '#ef4444',
    background: '#e2e8f0',
    text: '#0f172a',
    fontFamily: 'serif',
    borderRadius: '4px',
    borderWidth: '1px',
    shadow: '10px 10px 0px rgba(30, 41, 59, 0.2)',
    animationCurve: 'ease-in-out',
  },
];

export const TFDA_QUESTIONS: TFDAQuestion[] = [
  {
    id: 'src',
    textEn: 'Source of Medical Device',
    textZh: '醫療器材來源',
    type: 'select',
    options: [
      { value: 'domestic', labelEn: 'Domestic', labelZh: '國產' },
      { value: 'imported', labelEn: 'Imported', labelZh: '輸入' },
    ]
  },
  {
    id: 'risk',
    textEn: 'Risk Classification',
    textZh: '風險分級',
    type: 'select',
    options: [
      { value: 'class1', labelEn: 'Class I', labelZh: '第一等級' },
      { value: 'class2', labelEn: 'Class II', labelZh: '第二等級' },
      { value: 'class3', labelEn: 'Class III', labelZh: '第三等級' },
    ]
  },
  {
    id: 'mods',
    textEn: 'Modification Items',
    textZh: '變更項目',
    type: 'multi',
    options: [
      { value: 'name_device', labelEn: 'Device Name', labelZh: '品名變更' },
      { value: 'spec', labelEn: 'Specifications/Effect', labelZh: '規格、型號、效能變更' },
      { value: 'name_mfr', labelEn: 'Manufacturer Name', labelZh: '製造業者名稱變更' },
      { value: 'addr_mfr', labelEn: 'Manufacturer Address', labelZh: '製造業者地址變更' },
      { value: 'owner_change', labelEn: 'License Ownership Change', labelZh: '許可證移轉' },
      { value: 'add_mfr', labelEn: 'Add/Change Manufacturer', labelZh: '增加、變更委託/受託/另設廠製造業者' },
    ]
  },
  {
    id: 'fsc_needed',
    textEn: 'Is FSC (Free Sale Certificate) available?',
    textZh: '是否具備出產國許可製售證明(FSC)？',
    type: 'boolean',
    dependsOn: 'src',
    dependsValue: 'imported'
  },
  {
    id: 'tech_change',
    textEn: 'Does the specification change involve core technology?',
    textZh: '規格變更是否涉及核心技術？',
    type: 'boolean',
    dependsOn: 'mods',
    dependsValue: 'spec'
  }
];

export const TFDA_DOCS: TFDADocument[] = [
  { id: 'D1', nameEn: 'Application Form', nameZh: '醫療器材變更登記申請書', descriptionEn: 'Official application form.', descriptionZh: '官方申請書。' },
  { id: 'D2', nameEn: 'Original License', nameZh: '原醫療器材許可證正本', descriptionEn: 'The original paper license.', descriptionZh: '許可證正本。' },
  { id: 'D3', nameEn: 'FSC', nameZh: '出產國許可製售證明', descriptionEn: 'Free Sale Certificate from country of origin.', descriptionZh: '國外製售證明。' },
  { id: 'D4', nameEn: 'Comparison Table', nameZh: '變更對照表', descriptionEn: 'Before and after comparison.', descriptionZh: '變更前後對照表。' },
  { id: 'D10', nameEn: 'Technical Documents', nameZh: '技術資料', descriptionEn: 'Required for high risk or core changes.', descriptionZh: '高風險或核心變更所需技術文件。' },
  { id: 'D11', nameEn: 'Clinical Data', nameZh: '臨床資料', descriptionEn: 'Clinical evaluation or trials.', descriptionZh: '臨床評估或試驗資料。' },
];

export const INITIAL_RULES: ModificationRule[] = [
  {
    id: 'rule1',
    triggerQuestions: { src: 'imported', risk: 'class2', mods: ['spec'] },
    requiredDocs: ['D1', 'D2', 'D3', 'D4', 'D10'],
    notes: ['Must be verified by TECO office.', 'Note 7 triggers D10.']
  },
  {
    id: 'rule2',
    triggerQuestions: { src: 'domestic', risk: 'class1' },
    requiredDocs: ['D1', 'D2', 'D4'],
    notes: ['Simplified procedure.']
  }
];
